class Failure {
  const Failure([this.message = 'An unexpected error has occurred.']);

  final String message;
}
